// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article01: typeof import('./src/components/Article/Page/Article01.vue')['default']
    Article02: typeof import('./src/components/Article/Page/Article02.vue')['default']
    Article03: typeof import('./src/components/Article/Page/Article03.vue')['default']
    ArticleHeader: typeof import('./src/components/Article/ArticleHeader.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CardFooter: typeof import('./src/components/Card/CardFooter.vue')['default']
    CardTitle: typeof import('./src/components/Card/CardTitle.vue')['default']
    CareerPage: typeof import('./src/components/CareerPage.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MusicArticle01: typeof import('./src/components/Article/Page/MusicArticle01.vue')['default']
    MusicPage: typeof import('./src/components/MusicPage.vue')['default']
    NotePage: typeof import('./src/components/NotePage.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharingPage: typeof import('./src/components/SharingPage.vue')['default']
    TechArticle01: typeof import('./src/components/Article/Page/TechArticle01.vue')['default']
    TechPage: typeof import('./src/components/TechPage.vue')['default']
  }
}
